### ISSUE TITLE
exo4.3 + exo-staging-extension 2.3.1: ERROR | Cannot create the portal container 'portal' . 

### ISSUE THREAD

**Issue by chaos-prevails** [exo-addons/staging-extension#44]
Hello,

in exo4.3 (clean deployment), installing the exo-staging-extension (2.3.1) leads to the failure to create the portal container. Subsequently, requests to the server end with 503 error: "Server is starting, please try in a few seconds..., The requested service is not currently available."
The installation runs successfully and after uninstalling the extension, exo starts up normally again.

```
iamdpn@tesla:/var/exo43$ ./addon install exo-staging-extension

                  xx      xx 
                   xx    xx  
       eeeeeee      xx  xx      ooooooo
     ee       ee     xxxx     oo       oo  
    eeeeeeeeeeeee    xxxx    oo         oo 
    ee              xx  xx   oo         oo 
     ee       ee   xx    xx   oo       oo  
       eeeeeee    xx      xx    ooooooo       Add-ons Manager v1.0.2 
    
Reading catalog cache for http://www.exoplatform.com/addons/catalog .............................................. [OK]
Loading add-ons list ............................................................................................. [OK]
Checking compatibility of the add-on with your eXo platform instance ............................................. [OK]
[WARN]  DISCLAIMER : You are about to install third-party software available on your eXo Platform instance.
[WARN]  This software is provided "as is" without warranty of any kind, either expressed or implied and such software is to be used at your own risk. Use of this software is governed by its license and/or terms and conditions and it is your sole responsibility to accept and respect them prior to installing and using this software.
[WARN]  This software is not supported by eXo's Support Services.
Installing exo-staging-extension:2.3.1
File exo-staging-extension-2.3.1.zip already up-to-date. Skipping download. ...................................... [OK]
Checking add-on archive .......................................................................................... [OK]
Installing file webapps/gatein-management-cli.war ................................................................ [OK]
Installing file webapps/staging-extension-portlet.war ............................................................ [OK]
Installing file lib/staging-extension-common.jar ................................................................. [OK]
Installing file lib/staging-extension-service.jar ................................................................ [OK]
Installing file lib/staging-extension-uiextension.jar ............................................................ [OK]
Installing file lib/staging-extension-content.jar ................................................................ [OK]
Installing file lib/staging-extension-ecmadmin.jar ............................................................... [OK]
Installing file lib/staging-extension-site.jar ................................................................... [OK]
Installing file lib/staging-extension-gadget.jar ................................................................. [OK]
Installing file lib/staging-extension-registry.jar ............................................................... [OK]
Installing file lib/staging-extension-organization.jar ........................................................... [OK]
Installing file lib/staging-extension-wiki.jar ................................................................... [OK]
Installing file lib/staging-extension-answer.jar ................................................................. [OK]
Installing file lib/staging-extension-forum.jar .................................................................. [OK]
Installing file lib/staging-extension-calendar.jar ............................................................... [OK]
Installing file lib/staging-extension-social.jar ................................................................. [OK]
Installing file lib/staging-extension-config.jar ................................................................. [OK]
Installing file lib/gatein-management-api-1.1.0.Final.jar ........................................................ [OK]
Installing file lib/gatein-management-spi-1.1.0.Final.jar ........................................................ [OK]
Installing file lib/gatein-management-core-1.1.0.Final.jar ....................................................... [OK]
Installing file lib/gatein-management-rest-1.1.0.Final.jar ....................................................... [OK]
Recording installation details into exo-staging-extension.status ................................................. [OK]
Add-on exo-staging-extension:2.3.1 installed. .................................................................... [OK]
```
The whole log file is too big to post here, so I include only the error below. I added the whole logfile as pastebin: http://pastebin.com/kYVMVmgg
```
2016-02-10 11:51:15,596 | ERROR | Cannot create the portal container 'portal' . ServletContext: org.apache.catalina.core.ApplicationContextFacade@68d3f194 [exo.kernel.container.RootContainer<Catalina-startStop-1>] 
org.exoplatform.container.spi.ContainerException: Failed when calling start on org.exoplatform.services.rest.impl.ApplicationRegistry@1a72d45c
	at org.exoplatform.container.LifecycleVisitor.traverse(LifecycleVisitor.java:134) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.LifecycleVisitor.start(LifecycleVisitor.java:157) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.ConcurrentContainer.start(ConcurrentContainer.java:472) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.AbstractContainer.start(AbstractContainer.java:67) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.AbstractContainer.start(AbstractContainer.java:67) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.AbstractContainer.start(AbstractContainer.java:67) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.ExoContainer.start(ExoContainer.java:282) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.PortalContainer.start(PortalContainer.java:635) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.ExoContainer.start(ExoContainer.java:255) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.RootContainer.createPortalContainer(RootContainer.java:774) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.RootContainer.createPortalContainers(RootContainer.java:356) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.platform.server.tomcat.PortalContainersCreator$1.run(PortalContainersCreator.java:52) ~[plf-tomcat-pc-creator-listener-4.3.0.jar:4.3.0]
	at org.exoplatform.platform.server.tomcat.PortalContainersCreator$1.run(PortalContainersCreator.java:50) ~[plf-tomcat-pc-creator-listener-4.3.0.jar:4.3.0]
	at org.exoplatform.commons.utils.SecurityHelper.doPrivilegedAction(SecurityHelper.java:290) [exo.kernel.commons-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.platform.server.tomcat.PortalContainersCreator.createPortalContainers(PortalContainersCreator.java:50) [plf-tomcat-pc-creator-listener-4.3.0.jar:4.3.0]
	at org.exoplatform.platform.server.tomcat.PortalContainersCreator.lifecycleEvent(PortalContainersCreator.java:39) [plf-tomcat-pc-creator-listener-4.3.0.jar:4.3.0]
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117) [catalina.jar:7.0.63]
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90) [catalina.jar:7.0.63]
	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:402) [catalina.jar:7.0.63]
	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:347) [catalina.jar:7.0.63]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:1139) [catalina.jar:7.0.63]
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:819) [catalina.jar:7.0.63]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:7.0.63]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1574) [catalina.jar:7.0.63]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1564) [catalina.jar:7.0.63]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_95]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_95]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_95]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_95]
Caused by: java.lang.RuntimeException: Cannot instantiate component key=org.gatein.management.rest.RestApplication type=org.gatein.management.rest.RestApplication found at jar:file:/var/exo43/lib/exo.portal.component.management-4.3.0-PLF.jar!/conf/portal/configuration.xml
	at org.exoplatform.container.jmx.MX4JComponentAdapter.create(MX4JComponentAdapter.java:544) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.management.ManageableComponentAdapter.create(ManageableComponentAdapter.java:98) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.jmx.MX4JComponentAdapter.create(MX4JComponentAdapter.java:483) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.jmx.MX4JComponentAdapter.getComponentInstance(MX4JComponentAdapter.java:141) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.ConcurrentContainer.getInstance(ConcurrentContainer.java:446) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.ConcurrentContainer.getComponentInstancesOfType(ConcurrentContainer.java:328) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.AbstractContainer.getComponentInstancesOfType(AbstractContainer.java:147) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.CachingContainer.getComponentInstancesOfType(CachingContainer.java:92) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.AbstractContainer.getComponentInstancesOfType(AbstractContainer.java:147) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.AbstractContainer.getComponentInstancesOfType(AbstractContainer.java:147) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.services.rest.impl.ApplicationRegistry.start(ApplicationRegistry.java:83) ~[exo.ws.rest.core-2.4.4-GA.jar:2.4.4-GA]
	at sun.reflect.GeneratedMethodAccessor92.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_95]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_95]
	at org.exoplatform.container.LifecycleVisitor.traverse(LifecycleVisitor.java:98) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	... 28 common frames omitted
Caused by: java.lang.RuntimeException: Cannot instantiate component key=org.gatein.management.api.controller.ManagementController type=org.gatein.management.core.api.controller.SimpleManagementController found at jar:file:/var/exo43/lib/exo.portal.component.management-4.3.0-PLF.jar!/conf/portal/configuration.xml
	at org.exoplatform.container.jmx.MX4JComponentAdapter.create(MX4JComponentAdapter.java:544) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.management.ManageableComponentAdapter.create(ManageableComponentAdapter.java:98) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.jmx.MX4JComponentAdapter.create(MX4JComponentAdapter.java:483) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.jmx.MX4JComponentAdapter.getComponentInstance(MX4JComponentAdapter.java:141) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.ConcurrentContainer.getInstance(ConcurrentContainer.java:446) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.ConcurrentContainer.getComponentInstanceOfType(ConcurrentContainer.java:394) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.AbstractContainer.getComponentInstanceOfType(AbstractContainer.java:99) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.CachingContainer.getComponentInstanceOfType(CachingContainer.java:144) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.AbstractContainer.getComponentInstanceOfType(AbstractContainer.java:99) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.AbstractContainer.getComponentInstanceOfType(AbstractContainer.java:99) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.ExoContainer.getComponentInstanceOfType(ExoContainer.java:629) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.ExoContainer.getComponentInstanceOfType(ExoContainer.java:614) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.ConcurrentContainer.createComponent(ConcurrentContainer.java:596) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.AbstractContainer.createComponent(AbstractContainer.java:213) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.AbstractContainer.createComponent(AbstractContainer.java:213) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.AbstractContainer.createComponent(AbstractContainer.java:213) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.jmx.MX4JComponentAdapter$2.run(MX4JComponentAdapter.java:277) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.commons.utils.SecurityHelper.doPrivilegedExceptionAction(SecurityHelper.java:310) [exo.kernel.commons-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.jmx.MX4JComponentAdapter.createInstance(MX4JComponentAdapter.java:269) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.jmx.MX4JComponentAdapter.create(MX4JComponentAdapter.java:528) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	... 42 common frames omitted
Caused by: org.exoplatform.container.spi.ContainerException: Several ComponentAdapter found for interface org.gatein.management.api.ExternalContext
	at org.exoplatform.container.ConcurrentContainer.getComponentAdapterOfType(ConcurrentContainer.java:191) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.ConcurrentContainer.getComponentInstanceOfType(ConcurrentContainer.java:390) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.AbstractContainer.getComponentInstanceOfType(AbstractContainer.java:99) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.CachingContainer.getComponentInstanceOfType(CachingContainer.java:144) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.AbstractContainer.getComponentInstanceOfType(AbstractContainer.java:99) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.AbstractContainer.getComponentInstanceOfType(AbstractContainer.java:99) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.ExoContainer.getComponentInstanceOfType(ExoContainer.java:629) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.ExoContainer.getComponentInstanceOfType(ExoContainer.java:614) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.ConcurrentContainer.createComponent(ConcurrentContainer.java:596) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.AbstractContainer.createComponent(AbstractContainer.java:213) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.AbstractContainer.createComponent(AbstractContainer.java:213) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.AbstractContainer.createComponent(AbstractContainer.java:213) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.jmx.MX4JComponentAdapter$2.run(MX4JComponentAdapter.java:277) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.commons.utils.SecurityHelper.doPrivilegedExceptionAction(SecurityHelper.java:310) [exo.kernel.commons-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.jmx.MX4JComponentAdapter.createInstance(MX4JComponentAdapter.java:269) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	at org.exoplatform.container.jmx.MX4JComponentAdapter.create(MX4JComponentAdapter.java:528) ~[exo.kernel.container-2.5.4-GA.jar:2.5.4-GA]
	... 61 common frames omitted
2016-02-10 11:51:15,596 | WARN  | The portal container 'portal' doesn't exist or it has not yet been registered, please check your PortalContainerDefinitions and the loading order. [exo.kernel.container.RootContainer<Catalina-startStop-1>] 
2016-02-10 11:51:15,625 | INFO  | Starting ProtocolHandler ["http-nio-0.0.0.0-8080"] [o.apache.coyote.http11.Http11NioProtocol<main>] 
2016-02-10 11:51:15,627 | INFO  | Using a shared selector for servlet write/read [o.apache.tomcat.util.net.NioSelectorPool<main>] 
2016-02-10 11:51:15,705 | INFO  | Starting ProtocolHandler ["ajp-bio-0.0.0.0-8009"] [org.apache.coyote.ajp.AjpProtocol<main>] 
2016-02-10 11:51:15,731 | INFO  | Server startup in 206438 ms [org.apache.catalina.startup.Catalina<main>] 
```

**Comment by boubaker** [comment]
Hello,

The version 2.3 is not compatible with eXo Platform 4.3.
The version 2.5 of Staging Extension is not yet released for eXo Platform 4.3.

To test it, you can use this package:
https://repository.exoplatform.org/content/groups/public/org/exoplatform/addons/staging/staging-extension-packaging/2.5.x-SNAPSHOT/staging-extension-packaging-2.5.x-20160210.110029-36.zip

Best regards,
Boubaker Khanfir.

**Comment by chaos-prevails** [comment]
Hi Boubaker,

thank you. How can I use/install the addon as zip? I tried simply copying the lib and webapps files to their respective directories but the addon does not show up. Do I have to add a page which includes this portlet/gadget?
When I install the addon (2.3.1) via ./addon install and overwrite the installed files with those from the zip file (v2.5), eXo still doesn't start up.

Tim

**Comment by boubaker** [comment]
Hi,
Yes you can install it from ZIP file, but you should delete all previously added files including "gatein-management-*-1.1.0.Final.jar". The version of this API is different in eXo Platform 4.3 (btw, it's 2.1).
If this doesn't work, can you please paste the stack trace here.

I hope this helps.

Best regards.

**Comment by dvrcapture** [comment]
Hi,
I have the same issue here with the extention generator.
The link is also broken. Can u please share the newest version again. 

Best regards,
Thanks
